
# Model hyperparameters
model_name : hubert
ckpt_save_path : ./ckpts
ckpt_path : ./ckpts
report_path : ./reports
learning_rate: 2e-5
batch_size: 32
num_epochs: 5
gamma : 0.9
step_size : 1
ckpt_save_freq : 1
meanonnotzero: False

# Dataset parameters
dataset:
  path: ./datasets/